# Generated by Django 3.2.3 on 2021-06-07 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puco', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Cliente2',
        ),
    ]
