# Generated by Django 3.1.2 on 2021-05-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
