# Generated by Django 3.2.3 on 2021-06-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puco', '0002_auto_20210527_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut', models.CharField(max_length=10)),
                ('Nombres', models.CharField(max_length=50)),
                ('Correo', models.EmailField(max_length=50)),
                ('Telefono', models.CharField(max_length=50)),
                ('Asunto', models.CharField(max_length=100)),
            ],
        ),
    ]
