# Generated by Django 3.2.3 on 2021-06-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puco', '0003_auto_20210607_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nikename',
            field=models.CharField(default=123, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
