# Generated by Django 3.2.3 on 2021-06-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puco', '0004_cliente_nikename'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
    ]
