# Generated by Django 3.1.1 on 2021-06-17 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puco', '0007_auto_20210607_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('P', 'Perro'), ('G', 'Gato')], max_length=1)),
                ('edad', models.CharField(max_length=2)),
                ('tamano', models.CharField(choices=[('P', 'Pequeño'), ('M', 'Mediano'), ('G', 'Grande')], max_length=1)),
                ('peso', models.CharField(max_length=2)),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puco.cliente')),
            ],
        ),
    ]
