# Generated by Django 3.2.3 on 2021-07-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puco', '0009_alter_producto_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Text', models.CharField(max_length=50)),
                ('precio', models.IntegerField(max_length=10)),
                ('imagen', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
