# Generated by Django 3.2.3 on 2021-07-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puco', '0012_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tamano',
            field=models.CharField(choices=[('P', 'Pequeño'), ('M', 'Mediano'), ('G', 'Grande')], default='P', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('P', 'Perro'), ('G', 'Gato')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
