# Generated by Django 3.1.1 on 2021-07-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puco', '0013_auto_20210704_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='rut',
            field=models.CharField(max_length=10),
        ),
    ]
